name: Create Release

# On push to master branch. i.e. when we merge a PR.
on:
  push:
    branches: [ master, wtg-net10 ]
  pull_request:
    branches: [ master, wtg-net10 ]
  workflow_dispatch:

env:
  PACKAGE_PATH: Bin/Release/**/*.nupkg

jobs:
  release:
    name: Build - Release

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            10.0.x

      # Finds the latest release and increases the version
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch

    - name: Install dependencies
      run: dotnet restore WinformsLegacy.sln

      # Pacakge is created on build
    - name: Build
      run: >
        dotnet build WinformsLegacy.sln
        --configuration Release
        --no-restore
        /p:PackageVersion=${{ steps.version.outputs.version }}

      # Upload package as an atrifact to the GitHub action
    - name: Upload packages artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ${{ env.PACKAGE_PATH }}
        retention-days: 5

      # Create a new release and upload the package to the release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PACKAGE_PATH }}
        tag_name: ${{ steps.version.outputs.version }}

    - name: Push NuGet Package to NuGet Gallery
      run: dotnet nuget push ${{ env.PACKAGE_PATH }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
